### PR TITLE
Upgrade to napi v2

### PR DESCRIPTION
**Pull request by Brooooooklyn**
The return value from `async fn` is `String` represent **JavaScript Primitive**, so there is no need `env.adjust_external_memory`.

### CODE REVIEW

**Comment by pimeys** [comment]
Oh cool! It's getting near to be ready. Is there some testing plan we should do with this to give us a warning about regressions? I'll give it a thorough review when it's ready, but already looks much nicer api as before. And I'd like @cprieto to help me reviewing this, because we need more than one person understanding this part of the codebase.

For other Prisma members as a note, @Brooooooklyn is the author of napi-rs and this PR should be merged and tested thoroughly, and hopefully more than a week before we cut a release.

**Comment by Brooooooklyn** [comment]
@pimeys The upgraded API should be identical with the previous version. So I think we can test it in two sides:

1. The napi-rs v2 version should passed every tests in https://github.com/prisma/prisma.
2. We need to setup a minimal project to verify the remove of `adjust_external_memory` is worked as expect.

**Comment by Brooooooklyn** [comment]
I'll keep this merge request as `Draft` before all the other projects pass the ***napi-rs v2 upgrade*** testing.

**Comment by pimeys** [comment]
I'll be having a vacation in a few days for the rest of the year. 3.7.0 will be out on 21.12.2021, 3.8.0 on 11.1.2022. If most of us will be gone soon anyhow, what about merging this when we get back to work after New Year's party in 2.1.2022?

**Comment by pimeys** [comment]
I'm currently reading the changelog between 1.7.3 to 2.0.0-beta3 to understand the changes :)

**Comment by Brooooooklyn** [comment]
> I'm currently reading the changelog between 1.7.3 to 2.0.0-beta3 to understand the changes :)

I'll write a blog in next few days to explain everything in 2.0, including the new `#[napi] macro` API and breaking changes.

**Comment by pimeys** [comment]
I created a new branch on our fork so we get buildkite, release pipeline and the e2e javascript tests to run.

https://github.com/prisma/prisma-engines/pull/2477

**Comment by pimeys** [comment]
I started a local PR to get our buildkite tests running, being able to do an integration release build to npm and trigger our javascript e2e test suite.

https://github.com/prisma/prisma-engines/pull/2478

**Comment by pimeys** [comment]
Build/release error:

**Comment by Brooooooklyn** [comment]
@pimeys It would be resolved if you upgrade to rust@1.57  https://github.com/rust-lang/rust/commit/60fe8b3a65be709fe2163b8ab438ef14209055cc
Can you upgrade rust version?

**Comment by pimeys** [comment]
So, some results. Fails in the same tests as the current main branch does. So looks good. When you modify this, I'll try to remember to review and rebase my branch so we can keep the tests running.

https://github.com/prisma/e2e-tests/actions/runs/1554606913

I'm off for vacations very soon, so I'm not super available from tomorrow on.

**Comment by Brooooooklyn** [comment]
> I'm off for vacations very soon, so I'm not super available from tomorrow on.

Enjoy your vacation 🎉

**Comment by Brooooooklyn** [comment]
I think this one is ready for testing.

**Comment by Brooooooklyn** [comment]
https://napi.rs/blog/announce-v2 here is what's new in v2

**Comment by pimeys** [comment]
I will merge it next week when I'm back working and we have some time to see regressions if they happen.

**Comment by cprieto** [comment]
@Brooooooklyn we are facing problems with our integration tests and this PR, tests are failing with the following message:

```
node[34827]: ../src/env-inl.h:1172:void node::Environment::AddCleanupHook(node::Environment::CleanupCallback, void *): Assertion `(insertion_info.second) == (true)' failed.
 1: 0x10105447c node::Abort() [/opt/homebrew/bin/node]
 2: 0x101054460 node::Abort() [/opt/homebrew/bin/node]
 3: 0x100f92474 node::Environment::AddCleanupHook(void (*)(void*), void*) [/opt/homebrew/bin/node]
 4: 0x101022f1c napi_add_env_cleanup_hook [/opt/homebrew/bin/node]
 5: 0x116146530 napi_register_module_v1 [/Users/prisma/prisma/node_modules/.pnpm/@prisma+engines@3.7.0-11.qe-napi-2-7d9243c73ade811196e360a14435eb4756076300/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node]
 6: 0x101022b94 napi_module_register_by_symbol(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>, napi_value__* (*)(napi_env__*, napi_value__*)) [/opt/homebrew/bin/node]
 7: 0x10102715c std::__1::__function::__func<node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)::$_0, std::__1::allocator<node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)::$_0>, bool (node::binding::DLib*)>::operator()(node::binding::DLib*&&) [/opt/homebrew/bin/node]
 8: 0x10102695c node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/opt/homebrew/bin/node]
 9: 0x101208590 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/opt/homebrew/bin/node]
10: 0x101208204 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/opt/homebrew/bin/node]
11: 0x101207ce4 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/opt/homebrew/bin/node]
12: 0x100ec784c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/opt/homebrew/bin/node]
13: 0x100e5c2b8 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
14: 0x10581c90c
15: 0x106329960
16: 0x106712120
17: 0x10581367c
18: 0x105ccf714
19: 0x106b7187c
20: 0x106b9dbb0
21: 0x100e5c2b8 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
22: 0x100e8a994 Builtins_AsyncFunctionAwaitResolveClosure [/opt/homebrew/bin/node]
23: 0x100f0f818 Builtins_PromiseFulfillReactionJob [/opt/homebrew/bin/node]
24: 0x100e7cd74 Builtins_RunMicrotasks [/opt/homebrew/bin/node]
25: 0x100e59fa4 Builtins_JSRunMicrotasksEntry [/opt/homebrew/bin/node]
26: 0x101299774 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/opt/homebrew/bin/node]
27: 0x101299ae0 v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/opt/homebrew/bin/node]
28: 0x1012bae14 v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/opt/homebrew/bin/node]
29: 0x1012bac40 v8::internal::MicrotaskQueue::PerformCheckpointInternal(v8::Isolate*) [/opt/homebrew/bin/node]
30: 0x100e5dbd4 Builtins_CallApiCallback [/opt/homebrew/bin/node]
31: 0x1065d3808
32: 0x100e5a0cc Builtins_JSEntryTrampoline [/opt/homebrew/bin/node]
33: 0x100e59d64 Builtins_JSEntry [/opt/homebrew/bin/node]
34: 0x1012997ac v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/opt/homebrew/bin/node]
35: 0x101298dac v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/opt/homebrew/bin/node]
36: 0x1011c3bb0 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/opt/homebrew/bin/node]
37: 0x100f8bd20 node::InternalCallbackScope::Close() [/opt/homebrew/bin/node]
38: 0x100f8c51c node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/opt/homebrew/bin/node]
39: 0x100fa6df0 node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/opt/homebrew/bin/node]
40: 0x101103ff8 node::StreamBase::CallJSOnreadMethod(long, v8::Local<v8::ArrayBuffer>, unsigned long, node::StreamBase::StreamBaseJSChecks) [/opt/homebrew/bin/node]
41: 0x101104284 node::EmitToJSStreamListener::OnStreamRead(long, uv_buf_t const&) [/opt/homebrew/bin/node]
42: 0x10110ae7c node::LibuvStreamWrap::OnUvRead(long, uv_buf_t const*) [/opt/homebrew/bin/node]
43: 0x10326eb5c uv__stream_io [/opt/homebrew/opt/libuv/lib/libuv.1.dylib]
44: 0x103275ac4 uv__io_poll [/opt/homebrew/opt/libuv/lib/libuv.1.dylib]
45: 0x1032666c4 uv_run [/opt/homebrew/opt/libuv/lib/libuv.1.dylib]
46: 0x100f8cd80 node::SpinEventLoop(node::Environment*) [/opt/homebrew/bin/node]
47: 0x101091ed0 node::NodeMainInstance::Run(int*, node::Environment*) [/opt/homebrew/bin/node]
48: 0x101091b24 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/opt/homebrew/bin/node]
49: 0x101022118 node::Start(int, char**) [/opt/homebrew/bin/node]
50: 0x1904a5430 start [/usr/lib/system/libdyld.dylib] note
```

I tried updating the client and the same problem happens. Interestingly, the problem only ocurrs in [macOS Big Sur](https://en.wikipedia.org/wiki/MacOS_Big_Sur) in both Intel and Apple silicon, and I tested with every version of NodeJS from version 16.1 to 17.5

I had been looking around and I cannot find a reason for this, any help would be highly appreciated.

**Comment by cprieto** [comment]
Thanks @Brooooooklyn, I am in Discord if you need any help or have any question.

**Comment by Brooooooklyn** [comment]
Fixing it in https://github.com/napi-rs/napi-rs/pull/1081

**Pull request closed without merging**
