### PR TITLE
Allow comments in datasources

### PR DESCRIPTION
**Pull request by pimeys**
Only a failing test for now

### CODE REVIEW

**Comment by Jolg42** [comment]
Related https://github.com/prisma/prisma2/issues/1905

**Comment by Sytten** [comment]
This test should be working now

**Comment by janpio** [comment]
I think the test disagrees ;) Sorry.

**Comment by Sytten** [comment]
Weird because this is merged: https://github.com/prisma/prisma-engines/commit/8cec25ad6f57cecff56b90a09776569c3cebc957

**Comment by mavilein** [comment]
@Sytten is right. This was fixed. There's a test for this on master.

**Pull request closed without merging**
