### PR TITLE
chore: deprecate the cockroachdb preview feature

### PR DESCRIPTION
**Pull request by tomhoule**
The cockroach connector is no longer preview.

### CODE REVIEW

**Comment by Jolg42** [comment]
I think there are more source code mentions of `previewFeatures = ["cockroachdb"]` around

**Comment by tomhoule** [comment]
But I need to update a few more snapshots anyway (I think crdb tests are going to fail), let's do this.

**Comment by pimeys** [comment]
> > One more round of rg cockroachDb to find the usages in tests?
> 
> We don't need to remove all uses of the preview feature in tests to merge this, it's still valid.

More red to the PR the better, eh?

**Comment by tomhoule** [comment]
done, and it should pass CI now

**Pull request merged**
