### PR TITLE
Error if using CDB with PostgreSQL connector

### PR DESCRIPTION
**Pull request by pimeys**
- But only if the preview feature is enabled
- Otherwise it just (silently) keeps working as before

Closes: https://github.com/prisma/prisma/issues/11350

### CODE REVIEW

**Review by tomhoule — COMMENTED** [review]
The preview ends next tuesday — do we want a hard break, then? I assume not because we have big users on crdb with the cockroach provider. We'll keep the preview feature around, but deprecated, so that branch will likely never be taken. Wdyt? It does no harm so I can just approve, but we have to make the implications clear.

**Comment by pimeys** [comment]
Making this to error for everybody is a large change breaking many tests. We should do that in Prisma 4 I think...

**Comment by tomhoule** [comment]
There's a test checking that it's still possible, so let's wait until at least Prisma 4 to break, all good :+1:

**Review by tomhoule — APPROVED** [review]

**Comment by tomhoule** [comment]
The bad crash has been gone for months, iirc.

**Comment by janpio** [comment]
Follow up: https://prisma-company.slack.com/archives/C02K246T9RQ/p1651773693912689?thread_ts=1651674032.873609&cid=C02K246T9RQ

**Pull request merged**
