### PR TITLE
Trigger a warning if using type aliases

### PR DESCRIPTION
**Pull request by pimeys**
Warning is visible through `prisma-fmt`.

Closes: https://github.com/prisma/migrations-team/issues/275

### CODE REVIEW

**Comment by Jolg42** [comment]
Do you mean it will be visible with the following after it's done?
- `npx prisma format`
- VS Code extension warning

**Comment by pimeys** [comment]
I think it's only visible in LSP. We do not have a warning system in place for anything else, and agreed with @janpio we can at least have this for now.

**Review by tomhoule — APPROVED** [review]
lgtm :+1:

**Comment by janpio** [comment]
We should def understand better how exactly this is made visible in Language Server and how _not_ in `prisma format`.

**Comment by pimeys** [comment]
So basically we have no way to print warnings as we do for errors. The only place where we output them is the `lint` command in `prisma-fmt`, and that talks the LSP protocol, returning errors and warnings to the language server.

https://github.com/prisma/prisma-engines/blob/master/prisma-fmt/src/lint.rs#L27-L40

Format just outputs a formatted data model:

https://github.com/prisma/prisma-engines/blob/master/prisma-fmt/src/format.rs

Everywhere where we validate a datamodel, we break on errors and use the pretty print functionality of error messages. We miss this structure completely for warnings.

**Comment by Jolg42** [comment]
Ok thanks for confirming :)

**Pull request merged**
