### PR TITLE
 Reconfigure certain introspection table tests to match Cockroach output

### PR DESCRIPTION
**Pull request by otan**
A bit new to rust, so if there's a better way of doing those if's let me know :)

### CODE REVIEW

**Comment by otan** [comment]
cc @tomhoule here's a crack at some stuff, im not sure what to do with the milestone check.
the README.md for the `make postgres|mysql|...` is out of date as well...

**Comment by tomhoule** [comment]
> cc @tomhoule here's a crack at some stuff, im not sure what to do with the milestone check.
the README.md for the make postgres|mysql|... is out of date as well...

I just added the milestone (no need to worry about this), the makefile is for the query engine, we can tackle that later, and same for the README. We discussed the PR, I just shared some feedback on slack.

**Comment by otan** [comment]
adjusted

**Review by tomhoule — COMMENTED** [review]
looks good to me, I'll let @do4gr have a look too

**Comment by otan** [comment]
i think i'll abandon this strategy; we're renaming our PKs and FKs to match the prisma expectations.
some other PRs coming soon :) !

**Pull request closed without merging**
