### PR TITLE
Add argument to mysql tinyInt native type

### LINKED ISSUE #1182: Add arguments to Mysql native type TINYINT

### PR DESCRIPTION
**Pull request by carmenberndt**
closes #1182

### CODE REVIEW

**Review by mavilein — APPROVED** [review]

**Comment by jamiebuilds** [comment]
Why close this?

**Comment by cfraz89** [comment]
Would be great to resurrect this. It addresses [https://github.com/prisma/prisma/issues/10067](https://github.com/prisma/prisma/issues/10067)

**Comment by janpio** [comment]
I made sure that this PR is visible in that issue and will be looked at when we get to that issue.

**Comment by sacru2red** [comment]
@carmenberndt Why this PR is closed?
#10067
We wanna use tinyint not bool

**Pull request closed without merging**
