### PR TITLE
feat(core): add fork of `cuid` with wasm32-unknown-unknown support

### PR DESCRIPTION
**Pull request by jkomyno**
This PR deprecates https://github.com/prisma/prisma-engines/pull/4217.

Is uses a [`cuid` fork](https://github.com/prisma/cuid-rust/tree/wasm32-support) that is compatible with `wasm32-unknown-unknown` targets (as long the `js` feature of the `getrandom` dependency is active). See [diff](https://github.com/mplanchard/cuid-rust/compare/master...prisma:cuid-rust:wasm32-support?expand=1).

It closes https://github.com/prisma/team-orm/issues/350. It closes https://github.com/prisma/team-orm/issues/282.

### In the `wasm32-support` branch of the `cuid-rust` fork

- Run `cargo test -p cuid -- collisions::test --ignored --test-threads=1`
- Run `cargo test -p cuid -- collisions::single_thread --ignored --test-threads=1`
- Run `nice -n -20 cargo bench`

### In this PR

- Running `cargo tree -p prisma-schema-build --target wasm32-unknown-unknown | grep cuid` should yield:

  ```sh
  ❯ cargo tree -p prisma-schema-build --target wasm32-unknown-unknown | grep cuid
  │   │   │   ├── cuid v1.3.2 (https://github.com/prisma/cuid-rust?branch=wasm32-support#81309f9a)
  │   │   │   │   ├── cuid-util v0.1.0 (https://github.com/prisma/cuid-rust?branch=wasm32-support#81309f9a)
  │   │   │   │   ├── cuid2 v0.1.2 (https://github.com/prisma/cuid-rust?branch=wasm32-support#81309f9a)
  │   │   │   │   │   ├── cuid-util v0.1.0 (https://github.com/prisma/cuid-rust?branch=wasm32-support#81309f9a)
  ```

  indicating that Prisma's `cuid` fork with `wasm32` support is pulled in the Wasm binary for `@prisma/prisma-schema-wasm`.

- Running `cargo tree -p query-engine-node-api -e features | grep getrandom` should yield:
  ```sh
  ❯ cargo tree -p query-engine-node-api -e features | grep getrandom
  │       │       │   ├── getrandom feature "default"
  │       │       │   │   └── getrandom v0.2.10
  │       │       │                       │   │   └── getrandom feature "default" (*)
  │       │   │   │   │   │   │   │   │           └── getrandom feature "default" (*)
  │       │   │   │   │   │   │   │   ├── rand feature "getrandom"
  │       │   │   │   │   │   │   │   │   └── rand_core feature "getrandom"
  │       │   │   │   │   │   │   │       ├── getrandom feature "std"
  │       │   │   │   │   │   │   │       │   └── getrandom v0.2.10 (*)
  │       │   │   │   │   │   │   │       └── rand_core feature "getrandom" (*)
  │       ├── getrandom feature "default" (*)
  │       │   │       └── uuid feature "getrandom"
  │   │   │           │   │           └── getrandom feature "default"
  │   │   │           │   │               └── getrandom v0.1.16
  │   │   │           │   ├── getrandom feature "default" (*)
  │   │   │               ├── rand feature "getrandom"
  │   │   │               │   ├── rand feature "getrandom_package"
  │   │   │               │   └── rand_core feature "getrandom"
  │   │   │                   ├── getrandom feature "std"
  │   │   │                   │   └── getrandom v0.1.16 (*)
  │   │   │                   └── rand_core feature "getrandom" (*)
  ```
  indicating that the napi.rs Query Engine uses the default features of `getrandom`, rather than `"js"`.

- Running `cargo tree -p prisma-schema-build -e features --target wasm32-unknown-unknown | grep getrandom` should yield:
  ```sh
  ❯ cargo tree -p prisma-schema-build -e features --target wasm32-unknown-unknown | grep getrandom
  │       │       │       │       │       │   │   │           └── getrandom feature "default"
  │       │       │       │       │       │   │   │               └── getrandom v0.2.10
  │       │       │       │       │       │   │   ├── rand feature "getrandom"
  │       │       │       │       │       │   │   │   └── rand_core feature "getrandom"
  │       │       │       │       │       │   │       ├── rand_core feature "getrandom" (*)
  │       │       │       │       │       │   │       └── getrandom feature "std"
  │       │       │       │       │       │   │           └── getrandom v0.2.10 (*)
  │       │       │       ├── getrandom feature "default" (*)
  │       │       │       ├── getrandom feature "js"
  │       │       │       │   ├── getrandom v0.2.10 (*)
  │       │       │       │   ├── getrandom feature "js-sys"
  │       │       │       │   │   └── getrandom v0.2.10 (*)
  │       │       │       │   └── getrandom feature "wasm-bindgen"
  │       │       │       │       └── getrandom v0.2.10 (*)
  │       │       │       │       │   │   └── getrandom feature "default" (*)
  │       │       │           └── uuid feature "getrandom"
  ```
  indicating that `@prisma/prisma-schema-wasm` would use the `"js"` feature of `getrandom`.

- Running `cargo build -p prisma-schema-build --target wasm32-unknown-unknown && echo $?` should exit with `0`.

## TODO:
- [x] Remove `wasm` branch in [https://github.com/prisma/cuid-rust](https://github.com/prisma/cuid-rust) after review.

### CODE REVIEW

**Review by janpio — COMMENTED** [review]
✅

**Review by miguelff — APPROVED** [review]

**Comment by miguelff** [comment]
Really clean! thank you! ❤️

**Comment by jkomyno** [comment]
Note: we can merge this once [these PRs](https://prisma-company.slack.com/archives/C04TW4A2H8C/p1698256854584949) are merged as well.

**Comment by miguelff** [comment]
There has been a regression in the number of failing tests for driver adapters. @jkomyno can you please look into it?

**Pull request merged**
