### PR TITLE
Enrich user facing error when switching providers

### PR DESCRIPTION
**Pull request by tomhoule**
closes https://github.com/prisma/prisma/issues/5181

### CODE REVIEW

**Comment by do4gr** [comment]
The shortened link is already outdated I think ;-) I also started working on this and updated the docs and at the same time the header the link goes to. It still kinda works since it takes you to the top of the page I think.

**Review by do4gr — APPROVED** [review]

**Comment by tomhoule** [comment]
The link appears to still be working on my end — I'll set myself a reminder to check it out in a few days and see if it's broken

**Comment by janpio** [comment]
Link would need to be fixed in the pris.ly redirector anyway, so 👍

**Comment by tomhoule** [comment]
Link is still working :+1:

**Pull request merged**
