### PR TITLE
Case insensitive filtering

### PR DESCRIPTION
**Pull request by dpetrick**
Changelog:
- Adds feature flag `insensitiveFilters`.
- Adds `mode` enum type to string filters, allows `default` or `insensitive`.
- Only postgres has any implementation at the moment, as SQLite doesn't reliably support insensitive filtering and MySQL is insensitive by default.
- Important: 
    - Assumes that MySQL 8 users do NOT use case sensitive collations.
    - Assumes that Postgres users do NOT use collations that don't know how to lowercase characters (e.g. the C collation).

### CODE REVIEW

**Comment by Jolg42** [comment]
https://github.com/prisma/prisma-client-js/issues/690

**Comment by filoscoder** [comment]
Is this feature available for 2.5 version and above? (2.4.x??)

**Comment by pantharshit00** [comment]
@filoscoder It is available in 2.5.0. Release notes are here, it is under a flag for now: https://github.com/prisma/prisma/releases/tag/2.5.0

**Comment by filoscoder** [comment]
> @filoscoder It is available in 2.5.0. Release notes are here, it is under a flag for now: https://github.com/prisma/prisma/releases/tag/2.5.0

Alright! Thanks for the reply @pantharshit00 👍

**Pull request merged**
