### PR TITLE
test(qe): sqlite in GH actions

### PR DESCRIPTION
**Pull request by miguelff**
Closes https://github.com/prisma/team-orm/issues/543

Compensates for https://github.com/prisma/engineer/pull/117

Needed for https://github.com/prisma/prisma-engines/pull/4423

### CODE REVIEW

**Comment by janpio** [comment]
https://github.com/prisma/prisma-engines/pull/4460/files 😆 (Close mine if you merge yours)

**Comment by miguelff** [comment]
I needed mine with version 3 for https://github.com/prisma/prisma-engines/pull/4423

**Review by janpio — COMMENTED** [review]
✅

**Comment by miguelff** [comment]
@janpio gave me the :+1: verbally on this one.

**Pull request merged**
