### PR TITLE
compile query connectors, query core, and request handlers to wasm

### PR DESCRIPTION
**Pull request by skyzh**
The only real commit is https://github.com/prisma/prisma-engines/commit/4789f8d4d4b5d7acad21bbee92786d5092c9ee1d, will rebase after #4095 gets merged.

proceeding https://github.com/prisma/prisma-engines/pull/4095, this PR compiles everything up to request-handlers to WASM.

```
cd query-engine/request-handlers
cargo build --target wasm32-unknown-unknown --no-default-features
```

* In `prisma-models` crate, cuid is removed from the `wasm_generator` feature flag, so that it won't be compiled (it depends on hostname).
* For crates that indirectly depends on `getrandom`, add a `js` feature flag.
* For query core, query connector, and request handler crates, add `native-connectors` feature flag for native compilation.

There are some known runtime errors within the updated crates in this PR after compiling to WASM, for example, `std::time::Instant` is not supported in browsers. We will resolve this in the next PR where all things can be compiled to WASM while they can work correctly in the browser.

### CODE REVIEW

**Comment by skyzh** [comment]
btw, running `cargo llvm-lines --target wasm32-unknown-unknown --no-default-features --release` on request-handlers shows that:

```
  Lines                 Copies              Function name
  -----                 ------              -------------
  150738                5925                (TOTAL)
   13328 (8.8%,  8.8%)    60 (1.0%,  1.0%)  combine::parser::sequence::<impl combine::parser::Parser for (A,B)>::parse_mode_impl
   10702 (7.1%, 15.9%)    38 (0.6%,  1.7%)  <(Y,Z) as combine::parser::choice::ChoiceParser>::parse_mode_choice
    4632 (3.1%, 19.0%)    88 (1.5%,  3.1%)  <combine::parser::combinator::Map<P,F> as combine::parser::Parser>::parse_mode_impl
    4000 (2.7%, 21.7%)    16 (0.3%,  3.4%)  alloc::raw_vec::RawVec<T,A>::grow_amortized
    3600 (2.4%, 24.1%)    60 (1.0%,  4.4%)  combine::parser::sequence::PartialState2<A,B>::add_errors::{{closure}}
    3210 (2.1%, 26.2%)    30 (0.5%,  4.9%)  combine::parser::sequence::PartialState2<A,B>::add_errors
    3054 (2.0%, 28.2%)    54 (0.9%,  5.8%)  combine::error::FastResult<T,E>::map
    3026 (2.0%, 30.2%)    30 (0.5%,  6.3%)  combine::parser::sequence::<impl combine::parser::Parser for (A,B)>::add_error
    2960 (2.0%, 32.2%)   370 (6.2%, 12.6%)  combine::parser::Parser::parse_mode
    1976 (1.3%, 33.5%)     4 (0.1%, 12.7%)  combine::parser::sequence::<impl combine::parser::Parser for (A,B,C,D)>::parse_mode_impl
    1564 (1.0%, 34.5%)    25 (0.4%, 13.1%)  core::iter::traits::iterator::Iterator::try_fold
    1502 (1.0%, 35.5%)     4 (0.1%, 13.1%)  combine::parser::sequence::<impl combine::parser::Parser for (A,B,C)>::parse_mode_impl
    1500 (1.0%, 36.5%)    21 (0.4%, 13.5%)  combine::parser::Parser::parse_stream_consumed
    1498 (1.0%, 37.5%)     2 (0.0%, 13.5%)  combine::parser::sequence::<impl combine::parser::Parser for (A,B,C,D,E,F)>::parse_mode_impl
    1452 (1.0%, 38.5%)     8 (0.1%, 13.7%)  <combine::parser::combinator::AndThen<P,F> as combine::parser::Parser>::parse_mode_impl
    1344 (0.9%, 39.4%)    40 (0.7%, 14.3%)  core::result::Result<T,E>::map
```

Dropping graphql support completely in WASM mode would reduce binary size a lot, I guess.

**Comment by skyzh** [comment]
dropping graphql support results in 1/3 code size (LLVM lines):

```
Lines                Copies              Function name
  -----                ------              -------------
  52192                2336                (TOTAL)
   1750 (3.4%,  3.4%)     7 (0.3%,  0.3%)  alloc::raw_vec::RawVec<T,A>::grow_amortized
    968 (1.9%,  5.2%)     2 (0.1%,  0.4%)  <&mut serde_json::de::Deserializer<R> as serde::de::Deserializer>::deserialize_any
    903 (1.7%,  6.9%)    27 (1.2%,  1.5%)  core::result::Result<T,E>::map
    900 (1.7%,  8.7%)    15 (0.6%,  2.2%)  <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::next
    810 (1.6%, 10.2%)     5 (0.2%,  2.4%)  alloc::raw_vec::RawVec<T,A>::allocate_in
    698 (1.3%, 11.6%)    11 (0.5%,  2.9%)  core::iter::traits::iterator::Iterator::try_fold
```

I'm implementing this using feature flags and it's a relatively small PR. I can submit it after this gets merged, or the Prisma team can decide the roadmap to optionally enable it.

**Comment by jkomyno** [comment]
> 

Could you perhaps ship a separate PR that drops support for GraphQL, and select the branch of this PR as your base branch?

**Comment by skyzh** [comment]
yep, it's not included in this PR and I'll ship a separate one. I cannot select this PR as base branch b/c it's in the neon repo.

**Comment by skyzh** [comment]
the commit is https://github.com/prisma/prisma-engines/commit/90625e842cf0b6a95e2f169b6e2b9f9e97ce8d12

**Comment by jkomyno** [comment]
Internal: reviewers can easily poke at this PR's code locally via https://github.com/prisma/prisma-engines/pull/4120.

**Pull request closed without merging**
