### PR TITLE
feat: include field native type attributes data to DMMF

### PR DESCRIPTION
**Pull request by pasha-vuiko**
Hi! 
This PR exposes schema field native type data to DMMF.

Very long awaited feature for many people and me 🙂

### CODE REVIEW

**Comment by jkomyno** [comment]
Hi @pasha-vuiko, thanks for this PR!
Can we please ask you to fix the [clippy tests](https://github.com/prisma/prisma-engines/actions/runs/11386262437/job/32467447451?pr=5009)?

**Comment by pasha-vuiko** [comment]
Yep, I'll try to fix them today

**Comment by aqrln** [comment]
> sweeeet, so now I'm supposed to update 137mb JSON to make the fallen unit tests work?😅

You just need to run the tests with `UPDATE_EXPECT=1` env var set

**Comment by aqrln** [comment]
`UPDATE_EXPECT=1 cargo test -p dmmf -F psl/all` — something like this

**Comment by pasha-vuiko** [comment]
@aqrln thank you so much for your suggestion, I pushed the new commit

**Comment by aqrln** [comment]
Nice, this looks good to me. Would you be willing to update the TypeScript side as well (type definitions + snapshots in tests)?

**Comment by pasha-vuiko** [comment]
yes, I already created the PR in the Prisma repo
https://github.com/prisma/prisma/pull/25324
Currently it has some type related errors on test run, because it generates JSON files based on old version of prisma-engines (without the DMMF native type exposing) so what should I do next? Is it possible to somehow 'point' the prisma TS part to Rust part from the current PR?

**Comment by pasha-vuiko** [comment]
excuse me, I'm a bit confused, what should I do next to make the tests work with new version prisma-engines locally and in the pipeline?

**Comment by aqrln** [comment]
You can cherry-pick the commit from https://github.com/prisma/prisma/pull/25653 in the client repo.

Locally you can also set `export PRISMA_QUERY_ENGINE_LIBRARY=/absolute/path/to/target/debug/libquery_engine.so` and `export PRISMA_SCHEMA_ENGINE_BINARY=/.../target/debug/schema-engine` instead.

**Review by aqrln — APPROVED** [review]

**Pull request merged**
