### PR TITLE
Quick diff improvement: explicit message on empty summary

### PR DESCRIPTION
**Pull request by tomhoule**

### CODE REVIEW

**Comment by Jolg42** [comment]
Would be good to have a simple test?

**Review by Jolg42 — APPROVED** [review]

**Comment by Jolg42** [comment]
No problem, it will be tested on CLI side anyway 👍🏼

**Comment by Jolg42** [comment]
Looks like something is failing @tomhoule

**Comment by tomhoule** [comment]
Ok we had test cases we empty diffs, it looks like. Will update the snapshots.

**Pull request merged**
