### PR TITLE
Refactor: fold1 → reduce

### PR DESCRIPTION
**Pull request by zifeo**
Reduce compilation warnings.

### CODE REVIEW

**Comment by garrensmith** [comment]
@zifeo thanks for this. I'm running the tests. If they all pass we should be good to go.

**Comment by zifeo** [comment]
@garrensmith failures seem unrelated to the change?

**Comment by garrensmith** [comment]
@zifeo we working on some CI fixes and then I will merge this.

**Review by garrensmith — APPROVED** [review]

**Comment by garrensmith** [comment]
Thank you for this.

**Pull request merged**
