### PR TITLE
Docs writing session: migrate FAQ and parser database terminology

### PR DESCRIPTION
**Pull request by tomhoule**
See individual commits and their messages for details.

### CODE REVIEW

**Comment by Jolg42** [comment]
Unrelated: is there any way you can skip the CI here? 

(`[skip ci]` maybe? or have a setting in the repo that ignores .md files maybe?)

**Comment by tomhoule** [comment]
It's on my list to read the github docs to find out, but I haven't had the time yet. If you have an idea, it would be super welcome.

**Comment by Jolg42** [comment]
Then from experience `[skip ci]` in title or description of commit works perfectly for GitHub Actions [since February 8th](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/)

**Comment by tomhoule** [comment]
Will try next time

**Pull request merged**
