### PR TITLE
Sync ME JSON-RPC documentation and implementation

### PR DESCRIPTION
**Pull request by tomhoule**
## What is this about?

- We have migration engine API docs in notion, but they are maintained manually and easily get out of sync. Furthermore, nobody is reading them.
- We are moving towards relying _more_ on JSON-RPC.
- We may want to have a programmatic API one day. We may want to generate typescript type definitions from 

Considering all this, it makes sense to have docs for the migrations engine JSON-RPC API, and that these docs are easy to find and stay in sync. 

This PR implements reference documentation from which docs and rust types for the interface are generated. It was prototyped in https://github.com/tomhoule/prisma-migration-engine-api-reference and evolved a lot until it reached the simplified form it takes in this PR.

## What does it look like?

The docs will be in the prisma-engines rustdocs that are published on github pages. That way, they will be automatically be kept up-to-date with zero extra automation. They look like this:

---

## Details for reviewers

- `rust_crate.rs` evolved a lot, and the structure it has now is a reflection of its troubled history. I'm open to suggestions on improvements there.
- We do the generation through a build script to avoid committing generated code to the repo.
- I will squash the commits on the branch before merging.
- The failing test on MySQL is the separate issue about the version upgrade, that @pimeys dealt with. It should go away automatically (?).

### CODE REVIEW

**Comment by Jolg42** [comment]
>Tom said:
>It will be in https://prisma.github.io/prisma-engines/docs/json-rpc-build/index.html when once it's merged to main.

😍

**Review by garrensmith — COMMENTED** [review]
This is really cool idea. Nicely done.

**Comment by tomhoule** [comment]
Merging since I have oral approval, this is blocking progress on our main sprint goal and the MySQL issue is being addressed in https://github.com/prisma/prisma-engines/pull/2610

**Comment by janpio** [comment]
Although merged the link mentioned before https://github.com/prisma/prisma-engines/pull/2603#issuecomment-1017241715 does not work.

**Comment by Jolg42** [comment]
@janpio just updated the link

**Pull request merged**
