### PR TITLE
fix(qe). Metrics: fix metrics duplicates

### PR DESCRIPTION
**Pull request by miguelff**
Fixes: https://github.com/prisma/prisma/issues/21069

In https://github.com/prisma/prisma-engines/pull/4193

The metrics prefixed with `prisma_` where registered alongside with those prefixed with `mobc_` (later to be renamed) the reason, which I also found correct during the review, was to allow initial values for the counters and guages to be recorded during initialization.

If `prisma_` metrics were not registered, the initial values would be discarded by the whitelisting check.

However this caused two things, two **different** metrics being registered, and due to the rename (`mobc_` -> `prisma_`) displayed twice. This is because the rename of the metrics only occurs when the snapshot of whatever was recorded is displayed. Until that moment, any underlying metric being recorded is not grouped, and two different metrics are recorded as-is (in two different keys) in the metrics registry.

The approach taken now is to only white list what we record, and only initialize what we record (`mobc_`) variants of the metrics. And let the rename happen when the metrics are presented.

### CODE REVIEW

**Comment by janpio** [comment]
The bug also showed two slightly different descriptionsfor the duplicated metric keys. Is that also fixed?
(I think our tests are not confirming that at all)

**Comment by miguelff** [comment]
We are preserving the descriptions in our metrics initialisation code, the others were coming from mobc. Ours use "datasource" instead of "database".

**Comment by miguelff** [comment]
Example metrics snapshot:

```
# HELP prisma_client_queries_total Total number of Prisma Client queries executed
# TYPE prisma_client_queries_total counter
prisma_client_queries_total 1

# HELP prisma_datasource_queries_total Total number of Datasource Queries executed
# TYPE prisma_datasource_queries_total counter
prisma_datasource_queries_total 1

# HELP prisma_pool_connections_closed_total Total number of Pool Connections closed
# TYPE prisma_pool_connections_closed_total counter
prisma_pool_connections_closed_total 0

# HELP prisma_pool_connections_opened_total Total number of Pool Connections opened
# TYPE prisma_pool_connections_opened_total counter
prisma_pool_connections_opened_total 1

# HELP prisma_client_queries_active Number of currently active Prisma Client queries
# TYPE prisma_client_queries_active gauge
prisma_client_queries_active 0

# HELP prisma_client_queries_wait Number of queries currently waiting for a connection
# TYPE prisma_client_queries_wait gauge
prisma_client_queries_wait 0

# HELP prisma_pool_connections_busy Number of currently busy Pool Connections (executing a database query)
# TYPE prisma_pool_connections_busy gauge
prisma_pool_connections_busy 0

# HELP prisma_pool_connections_idle Number of currently unused Pool Connections (waiting for the next pool query to run)
# TYPE prisma_pool_connections_idle gauge
prisma_pool_connections_idle 21

# HELP prisma_pool_connections_open Number of currently open Pool Connections
# TYPE prisma_pool_connections_open gauge
prisma_pool_connections_open 1

# HELP prisma_client_queries_duration_histogram_ms Histogram of the duration of all executed Prisma Client queries in ms
# TYPE prisma_client_queries_duration_histogram_ms histogram
prisma_client_queries_duration_histogram_ms_bucket{le="0"} 0
prisma_client_queries_duration_histogram_ms_bucket{le="1"} 0
prisma_client_queries_duration_histogram_ms_bucket{le="5"} 0
prisma_client_queries_duration_histogram_ms_bucket{le="10"} 0
prisma_client_queries_duration_histogram_ms_bucket{le="50"} 1
prisma_client_queries_duration_histogram_ms_bucket{le="100"} 1
prisma_client_queries_duration_histogram_ms_bucket{le="500"} 1
prisma_client_queries_duration_histogram_ms_bucket{le="1000"} 1
prisma_client_queries_duration_histogram_ms_bucket{le="5000"} 1
prisma_client_queries_duration_histogram_ms_bucket{le="50000"} 1
prisma_client_queries_duration_histogram_ms_bucket{le="+Inf"} 1
prisma_client_queries_duration_histogram_ms_sum 38.727
prisma_client_queries_duration_histogram_ms_count 1

# HELP prisma_client_queries_wait_histogram_ms Histogram of the wait time of all queries in ms
# TYPE prisma_client_queries_wait_histogram_ms histogram
prisma_client_queries_wait_histogram_ms_bucket{le="0"} 0
prisma_client_queries_wait_histogram_ms_bucket{le="1"} 2
prisma_client_queries_wait_histogram_ms_bucket{le="5"} 2
prisma_client_queries_wait_histogram_ms_bucket{le="10"} 2
prisma_client_queries_wait_histogram_ms_bucket{le="50"} 2
prisma_client_queries_wait_histogram_ms_bucket{le="100"} 2
prisma_client_queries_wait_histogram_ms_bucket{le="500"} 2
prisma_client_queries_wait_histogram_ms_bucket{le="1000"} 2
prisma_client_queries_wait_histogram_ms_bucket{le="5000"} 2
prisma_client_queries_wait_histogram_ms_bucket{le="50000"} 2
prisma_client_queries_wait_histogram_ms_bucket{le="+Inf"} 2
prisma_client_queries_wait_histogram_ms_sum 0.171583
prisma_client_queries_wait_histogram_ms_count 2

# HELP prisma_datasource_queries_duration_histogram_ms Histogram of the duration of all executed Datasource Queries in ms
# TYPE prisma_datasource_queries_duration_histogram_ms histogram
prisma_datasource_queries_duration_histogram_ms_bucket{le="0"} 0
prisma_datasource_queries_duration_histogram_ms_bucket{le="1"} 0
prisma_datasource_queries_duration_histogram_ms_bucket{le="5"} 0
prisma_datasource_queries_duration_histogram_ms_bucket{le="10"} 0
prisma_datasource_queries_duration_histogram_ms_bucket{le="50"} 1
prisma_datasource_queries_duration_histogram_ms_bucket{le="100"} 1
prisma_datasource_queries_duration_histogram_ms_bucket{le="500"} 1
prisma_datasource_queries_duration_histogram_ms_bucket{le="1000"} 1
prisma_datasource_queries_duration_histogram_ms_bucket{le="5000"} 1
prisma_datasource_queries_duration_histogram_ms_bucket{le="50000"} 1
prisma_datasource_queries_duration_histogram_ms_bucket{le="+Inf"} 1
prisma_datasource_queries_duration_histogram_ms_sum 26.610541
prisma_datasource_queries_duration_histogram_ms_count 1
```

**Comment by janpio** [comment]
> # HELP prisma_client_queries_wait Number of queries currently waiting for a connection
> # TYPE prisma_client_queries_wait gauge
> prisma_client_queries_wait 0

In our docs we have a different description for this one:
> Number of Prisma Client queries currently waiting for a connection

Our code also seems to have that one:
https://github.com/prisma/prisma-engines/blob/f4104c076ba453b09b6296a2533f7dbef7cc2157/query-engine/metrics/src/lib.rs#L169

**Comment by miguelff** [comment]
@Jan, as agreed I will address the descriptions problem in a different PR, given the regression is only the duplication.

**Review by Jolg42 — APPROVED** [review]
Thanks @miguelff for jumping on this fix 💚

**Pull request merged**
