### PR TITLE
Add onlyCreate boolean flag to create record operation

### PR DESCRIPTION
**Pull request by josethz00**
Prisma has an open issue that claims for the possibility to skip the default select query that is made after creating a record.

_Referred issue_: [4246](https://github.com/prisma/prisma/issues/4246)

As the first step to solve this, I have added a new parameter called `only_create`  to the `create_record` function. This parameter is a boolean option, and it will determine if the select query should be executed or not.

I am facing some problems running the unit tests on my machine, trying to solve this as soon as possible to ensure that all tests pass with this new change in the code.

### CODE REVIEW

**Review by victoriaquasar — APPROVED** [review]
LGTM

**Review by antoniolopesg — APPROVED** [review]

**Comment by tomhoule** [comment]
Hi @josethz00 , thank you for taking a shot at closing that issue! We appreciate the care and effort.

Unfortunately, it will take a lot more work to solve this problem properly. There has to be a design phase that looks at the whole problem, not only for what the Client API side of this should look like, but also how it interacts with other features, type generation, etc. We start with a proper (internal) technical spec when we are ready to tackle a feature like this, and it's a lot of work. Onboarding a new contributor on the problem space and the codebase, and reviewing their design and their code, is even more work. For now, the right avenue for discussing the problem is in the prisma/prisma issue.

I hope we will get there in the future, but we currently cannot take contributions on issues like https://github.com/prisma/prisma/issues/4246.

**Comment by josethz00** [comment]
Sure, I understand, and thank you for the answer @tomhoule ! Please let me know if there is anything else that can be done about this issue 😄

**Comment by janpio** [comment]
(Please everyone ignore this misleading codspeed comment - I reported the bug to the tool but will leave it here so they can take a look.)

**Pull request closed without merging**
