### PR TITLE
fix(migration-engine): [Postgres] improve interoperability between raw ops and others

### PR DESCRIPTION
**Pull request by uhyo**
Fixes https://github.com/prisma/prisma/issues/16275.

Sometimes we need to specify `raw(...)` as an operator class even though Prisma knows it, specifically when the operator class is not compatible with Gin by default but is supported by the `btree_gin` extension.

This PR fixes the problem that in such cases Prisma Migrate tries to recreate Gin indexes with same definition.

### CODE REVIEW

**Comment by Druue** [comment]
Hey, thanks for the PR! Just going to take a look :)

**Review by Druue — CHANGES_REQUESTED** [review]
Hey, can you fix up the clippy errors. You can see these locally with `cargo clippy`.
Otherwise, looks good to me!

**Comment by uhyo** [comment]
Sorry for the clippy errors, fixed! :smiley:

**Comment by janpio** [comment]
I investigated a bit, and left a comment in the issue (as it also includes a lot of info about what is actually happening here): https://github.com/prisma/prisma/issues/16275#issuecomment-1402159146

**Comment by kibertoad** [comment]
@janpio So what is preventing this from landing?

**Comment by kibertoad** [comment]
@janpio Thank you for the explanation!

**Comment by uhyo** [comment]
Let me close this PR as this is unlikely to be merged, and I already left the team that keenly needed this fix 😬

**Pull request closed without merging**
