### PR TITLE
fix(errors): Mention correct db in postgres DatabaseDoesNotExist

### PR DESCRIPTION
**Pull request by tomhoule**
closes https://github.com/prisma/prisma/issues/11673

### CODE REVIEW

**Review by Jolg42 — APPROVED** [review]
@tomhoule Looks good but fails with `error: unnecessary use of `to_owned``

**Comment by Jolg42** [comment]
And there are many diffs to update?

**Comment by tomhoule** [comment]
This isn't ready yet

**Comment by tomhoule** [comment]
Ok now it's ready :)

**Comment by janpio** [comment]
(Side note: Why do we not split the schema out in the error message if that is part of the problem?)

**Comment by tomhoule** [comment]
Good point, the schema is irrelevant if it's really the database that doesn't exist. Let's just remove it.

**Pull request merged**
